version: '2'

services:
  jekyll:
    build:
      context: .
    image: weaveworksdemos/ms-docs
    command: jekyll serve --host 0.0.0.0 --watch --incremental
    environment:
      - JEKYLL_ENV=development
      - PAGES_REPO_NWO=aeroportos-onix/aeroportos-onix
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
